// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", false);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.user_id", "1349230c-e36b-4724-9105-633f321b0774");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1549825080);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1549825200);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1549816705);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1549824424);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1549816912);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1549824960);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1549825320);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 778240);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.ctrlTab.migrated", true);
user_pref("browser.ctrlTab.recentlyUsedOrder", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1549816675);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{295dc3ea-87b8-4b28-af9c-ca94f0168e57}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1549753200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"addSearchEngine\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1549824398720");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1549826168720");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1549824399455");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1549827999455");
user_pref("browser.search.countryCode", "HU");
user_pref("browser.search.region", "HU");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190128144255");
user_pref("browser.slowStartup.averageTime", 2152);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20190128144255");
user_pref("browser.startup.homepage_override.mstone", "65.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"feed-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.matchBuckets", "general:5,suggestion:Infinity");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1549816892896");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.performance.recording.interval", 1000);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "de2ac17bbddd4cea9a4a02df236be5cf");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.lastModified", "Fri, 08 Feb 2019 12:03:20 GMT");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1549825082);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190128144255");
user_pref("extensions.lastAppVersion", "65.0");
user_pref("extensions.lastPlatformVersion", "65.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{1856da8e-6e5b-4ebb-b054-d193346acaa0}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"0ee77015-789d-4e3f-8c4c-54d84fd6ee83\",\"formautofill@mozilla.org\":\"34038549-9e13-4877-81d1-844772aabc4d\",\"webcompat@mozilla.org\":\"f31d1188-244d-4cf7-9ca3-5a5a9c441688\",\"webcompat-reporter@mozilla.org\":\"b608baa0-5264-4220-b09b-db6cabd703e2\",\"fxmonitor@mozilla.org\":\"8753dc49-2a61-4342-8201-ac7210911014\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1549816924);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190128144255");
user_pref("media.gmp-manager.lastCheck", 1549824977);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "bcf4dc12-3ed7-476e-87ce-30150fb7cb24");
user_pref("security.sandbox.plugin.tempDirSuffix", "b0f22ffd-d471-4ada-bb1d-d2e24b4d4185");
user_pref("services.blocklist.addons.checked", 1549825049);
user_pref("services.blocklist.gfx.checked", 1549825049);
user_pref("services.blocklist.onecrl.checked", 1549825049);
user_pref("services.blocklist.pinning.checked", 1549825049);
user_pref("services.blocklist.plugins.checked", 1549825049);
user_pref("services.settings.clock_skew_seconds", -9);
user_pref("services.settings.last_etag", "\"1549649719840\"");
user_pref("services.settings.last_update_seconds", 1549824986);
user_pref("services.settings.main.language-dictionaries.last_check", 1549825049);
user_pref("services.settings.main.onboarding.last_check", 1549825049);
user_pref("services.settings.main.sites-classification.last_check", 1549825049);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1549824929);
user_pref("toolkit.telemetry.cachedClientID", "35b9ef1f-6ace-4988-b862-c036f8b9c105");
user_pref("toolkit.telemetry.previousBuildID", "20190128144255");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
